### ISSUE TITLE
Facebook  Login Failed

### ISSUE THREAD

**Issue by suhailiqbal23** [lucumt/facebookProfileSpider#1]
I am getting an error message Login Facebook failed! Please help me out..

**Comment by frankiechen1** [comment]
Im getting into this trouble as well. What program r u using to run his code, python or Eclipse?

**Comment by lucumt** [comment]
@frankiechen1 I am using pydev to run this program. The key point to run it success is that make sure you have the correct user cookie in the file https://github.com/lucumt/facebookProfileSpider/blob/master/fpspider/src/facebookLogin.py

BTW,can you guys start my project?

**Comment by lucumt** [comment]
I have updated the README.md file,people who login failed when running can check it!

**Comment by frankiechen1** [comment]
thanks for the updates, sir

**Comment by lucumt** [comment]
@frankiechen1 please star my project,buddy!
